language: en
pipeline:
- name: SpacyNLP
- name: SpacyTokenizer
- name: SpacyEntityExtractor
  dimensions:
  - GPE
  - PRODUCT
  - CARDINAL
  - MONEY
  - LOC
- name: RegexFeaturizer
- name: SpacyFeaturizer
  return_sequence: true
- name: CRFEntityExtractor
  return_sequence: true
- name: EntitySynonymMapper
- name: SklearnIntentClassifier
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: FormPolicy
- name: MappingPolicy
- name: FallbackPolicy
  nlu_threshold: 0.3
  ambiguity_threshold: 0.1
  core_threshold: 0.3
  fallback_action_name: action_default_fallback
